services:
  bot:
    build: .
    image: servicebot:latest
    restart: unless-stopped
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", 'node -e "process.exit(0)"']
      interval: 30s
      timeout: 5s
      retries: 3
